# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Nilay Karaoglu
paginate:       5
baseurl:        ""
url:            "https://eowyn36.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Nilay Karaoglu
  url:          https://eowyn36.github.io/
  email:        nilaya@kth.se

# Custom vars
version:        1
github:
  repo:         https://github.com/eowyn36/eowyn36.github.io

# Gems
gems:
  - jekyll-paginate

# Define data collections
collections:
  - pages
